### ISSUE TITLE
Website is currently down

### ISSUE THREAD

**Issue by cthoyt** [OpenBEL/openbel.github.io#6]
the only page on openbel.org that's loading right now is the homepage

**Comment by wshayes** [comment]
Hi Charles,

Is it still down?  There is now only the home page as we re-worked the website to point to reference documents in their home location.  The previous openbel.org website duplicated a fair amount of content on other pages/sites which was hard to keep up to date.  

Can you tell me what is missing that you are looking for?

**Comment by cthoyt** [comment]
Ah! I tried some of the links and they are working. However, the http://openbel.org/language/web/version_2.0/bel_specification_version_2.0.html and http://openbel.github.io/language/web/index.html links are still down. It would also be nice to have a link on the OpenBEL page to the 1.0 Specification, since the 2.0 Specification does not outline some of the things that did not change from one version to the other.

I applaud your effort to condense these resources to a manageable, central location.

**Comment by wshayes** [comment]
Thanks - sorry about that.  All fixed now.

**Comment by wshayes** [comment]
Added BEL 1.0 links as well.
